[build]
  command = "npm ci --include=dev && npm run netlify-build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "production" }

[context.visual-editor]
  command = "npm ci --include=dev && ENABLE_VISUAL_EDITOR=true npm run netlify-build"
  publish = "dist"
  environment = { NODE_ENV = "production", ENABLE_VISUAL_EDITOR = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200