[build]
  command = "npm ci --include=dev && npm run netlify-build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5175
  port = 8888
  publish = "dist"

[context.production]
  environment = {}

[context.deploy-preview]
  environment = {}

[context.visual-editor]
  command = "npm ci --include=dev && ENABLE_VISUAL_EDITOR=true npm run netlify-build"
  publish = "dist"
  environment = { ENABLE_VISUAL_EDITOR = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund --include=dev"