[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-vite"