[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5175
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  ENABLE_VISUAL_EDITOR = "true"
  CI = ""
  NPM_FLAGS = "--include=dev"