[build]
  command = "node stackbit-build.js"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200