backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }