backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "select", options: ["ImageIcon", "FileText", "TestTubes", "Palette", "Book", "CreditCard", "BarChart3", "Link2"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["Product Ad Images & Copywriting", "Brand Identity Design", "Digital Marketing Content"] }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Content", name: "body", widget: "markdown" }

local_backend: true